env: standard
runtime: nodejs18
instance_class: F4
service: fe-cinema-ticket-app
inbound_services:
- warmup
automatic_scaling:
    min_idle_instances: 1
    min_instances: 1
handlers:
  - url: /.*
    secure: always
    script: auto
    